# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zixun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.TextField(default='')),
                ('source', models.TextField(default='')),
                ('update_time', models.TextField(default='')),
                ('see_times', models.TextField(default='')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
