# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_zixun'),
    ]

    operations = [
        migrations.AddField(
            model_name='zixun',
            name='publish_status',
            field=models.IntegerField(default=0),
        ),
    ]
